apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app
  labels:
    app: inventario-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: inventario-app
      tier: base
  template:
    metadata:
      labels:
        app: inventario-app
        tier: base
    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/daft4less/inventario-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: STARTUP_DELAY_SECONDS
              value: "15"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: inventario-app-secret
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10